# Generated by Django 5.2.3 on 2025-07-19 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('options', models.CharField(max_length=255)),
                ('answer', models.CharField(max_length=100)),
            ],
        ),
    ]
